#include "mainwindow.h"
#include "filenotificationdialog.h"

#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QTextEdit>
#include <QPushButton>
#include <QLabel>
#include <QFileDialog>
#include <QMessageBox>
#include <QDir>
#include <QFile>
#include <QTextStream>
#include <QRandomGenerator>
#include <QStandardPaths>
#include <QCoreApplication>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , m_textEdit(new QTextEdit(this))
    , m_generateButton(new QPushButton("1. Generate 3 .dat files", this))
    , m_loadButton(new QPushButton("2. Load .dat files", this))
    , m_statusLabel(new QLabel("Ready.", this))
{
    setWindowTitle("QFileDialog + QDialog + QTimer Example");
    resize(720, 520);

    m_textEdit->setReadOnly(true);
    m_textEdit->setFontFamily("Courier New");

    QHBoxLayout *buttonLayout = new QHBoxLayout;
    buttonLayout->addWidget(m_generateButton);
    buttonLayout->addWidget(m_loadButton);
    buttonLayout->addStretch();

    QVBoxLayout *mainLayout = new QVBoxLayout;
    mainLayout->addLayout(buttonLayout);
    mainLayout->addWidget(m_textEdit);
    mainLayout->addWidget(m_statusLabel);

    QWidget *central = new QWidget(this);
    central->setLayout(mainLayout);
    setCentralWidget(central);

    connect(m_generateButton, &QPushButton::clicked,
            this, &MainWindow::onGenerateFilesClicked);
    connect(m_loadButton, &QPushButton::clicked,
            this, &MainWindow::onLoadFilesClicked);
}

MainWindow::~MainWindow() = default;

// ---------------------------------------------------------------
// Step 1: Generate 3 .dat files with random data
// ---------------------------------------------------------------
void MainWindow::onGenerateFilesClicked()
{
    // Ask the user where to save the generated files
    QString dir = QFileDialog::getExistingDirectory(
        this,
        "Choose a folder to generate .dat files",
        QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation));

    if (dir.isEmpty())
        return;

    if (generateRandomDatFiles(dir, 3, 20)) {
        m_statusLabel->setText(QString("Generated 3 .dat files in: %1").arg(dir));
        QMessageBox::information(this, "Success",
                                 "3 .dat files were created successfully.\n\n"
                                 "Now click 'Load .dat files' to load them.");
    } else {
        QMessageBox::warning(this, "Error", "Failed to generate .dat files.");
    }
}

bool MainWindow::generateRandomDatFiles(const QString &dir, int count, int linesPerFile)
{
    m_generatedFiles.clear();

    for (int i = 1; i <= count; ++i) {
        QString fileName = QString("data_%1.dat").arg(i);
        QString path = QDir(dir).filePath(fileName);

        QFile file(path);
        if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
            qWarning("Cannot open %s for writing", qPrintable(path));
            return false;
        }

        QTextStream out(&file);

        // Header line
        out << "# Random data file " << i << "\n";
        out << "# Generated by FileLoaderExample\n";

        // Random numeric data
        for (int line = 0; line < linesPerFile; ++line) {
            for (int col = 0; col < 4; ++col) {
                int value = QRandomGenerator::global()->bounded(0, 10000);
                out << value;
                if (col < 3)
                    out << '\t';
            }
            out << '\n';
        }

        file.close();
        m_generatedFiles << path;
    }
    return true;
}

// ---------------------------------------------------------------
// Step 2: Load the .dat files via QFileDialog, one at a time,
//         showing a QDialog notification for 8 s each.
// ---------------------------------------------------------------
void MainWindow::onLoadFilesClicked()
{
    m_textEdit->clear();

    const int totalFiles = 3;

    for (int i = 0; i < totalFiles; ++i) {
        // --- Show a QFileDialog for the i-th file ---
        QString caption = QString("Select .dat file %1 of %2")
                              .arg(i + 1).arg(totalFiles);

        QString path = QFileDialog::getOpenFileName(
            this,
            caption,
            QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation),
            "Data files (*.dat);;All files (*)");

        if (path.isEmpty()) {
            // User cancelled -> stop the whole loop
            m_statusLabel->setText(QString("Cancelled at file %1 of %2.")
                                       .arg(i + 1).arg(totalFiles));
            appendSeparator("Load cancelled by user");
            return;
        }

        // --- Show a QDialog notification for 8 seconds ---
        QString msg = QString("File %1 opened:\n%2")
                          .arg(i + 1)
                          .arg(QFileInfo(path).fileName());

        FileNotificationDialog dlg(msg, 8000, this);
        dlg.exec();     // Blocks until the 8 s QTimer fires and accept() is called

        // --- Read the file and append to the QTextEdit ---
        QFile file(path);
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
            QMessageBox::warning(this, "Error",
                                 QString("Could not open:\n%1").arg(path));
            continue;
        }

        QTextStream in(&file);
        QString contents = in.readAll();
        file.close();

        appendSeparator(QString("File %1: %2").arg(i + 1).arg(path));
        m_textEdit->append(contents);
    }

    m_statusLabel->setText("All 3 .dat files loaded.");
    appendSeparator("All files loaded");
}

void MainWindow::appendSeparator(const QString &title)
{
    m_textEdit->append(QString("\n================ %1 ================\n").arg(title));
}
